from alembic import op
import sqlalchemy as sa

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("email", sa.String(255), nullable=True, unique=True), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.create_table("technology_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False, unique=True), sa.Column("description", sa.Text(), nullable=True))
    op.create_table("technologies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False, unique=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("technology_categories.id"), nullable=False), sa.Column("language", sa.String(80), nullable=False), sa.Column("supports_ai", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("supports_realtime", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("learning_curve", sa.String(40), nullable=False), sa.Column("community", sa.String(40), nullable=False), sa.Column("performance", sa.String(40), nullable=False), sa.Column("cost", sa.String(40), nullable=False), sa.Column("official_url", sa.String(500), nullable=False), sa.Column("pros", sa.JSON(), nullable=False), sa.Column("cons", sa.JSON(), nullable=False), sa.Column("use_cases", sa.JSON(), nullable=False))
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("budget", sa.Integer(), nullable=False), sa.Column("expected_users", sa.Integer(), nullable=False), sa.Column("timeline", sa.String(40), nullable=False), sa.Column("team_size", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.create_table("questionnaire_responses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("responses", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.create_table("technology_knowledge_base", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("technology_id", sa.Integer(), sa.ForeignKey("technologies.id"), nullable=False), sa.Column("details", sa.JSON(), nullable=False))
    op.create_table("recommendation_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("technology_id", sa.Integer(), sa.ForeignKey("technologies.id"), nullable=False), sa.Column("conditions", sa.JSON(), nullable=False), sa.Column("positive_weight", sa.Integer(), nullable=False), sa.Column("negative_weight", sa.Integer(), nullable=False), sa.Column("compatibility_score", sa.Integer(), nullable=False), sa.Column("cost_score", sa.Integer(), nullable=False), sa.Column("scalability_score", sa.Integer(), nullable=False), sa.Column("learning_curve_score", sa.Integer(), nullable=False))
    op.create_table("compatibility_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_technology_id", sa.Integer(), sa.ForeignKey("technologies.id"), nullable=False), sa.Column("target_technology_id", sa.Integer(), sa.ForeignKey("technologies.id"), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("score", sa.Integer(), nullable=False), sa.Column("reason", sa.Text(), nullable=False))
    op.create_table("feature_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("trigger", sa.String(80), nullable=False), sa.Column("recommendations", sa.JSON(), nullable=False))
    op.create_table("recommendations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("architecture_pattern", sa.String(120), nullable=False), sa.Column("confidence", sa.Integer(), nullable=False), sa.Column("score_breakdown", sa.JSON(), nullable=False), sa.Column("explanation", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.create_table("recommendation_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("recommendation_id", sa.Integer(), sa.ForeignKey("recommendations.id"), nullable=False), sa.Column("technology_id", sa.Integer(), sa.ForeignKey("technologies.id"), nullable=False), sa.Column("role", sa.String(40), nullable=False), sa.Column("confidence", sa.Integer(), nullable=False), sa.Column("score", sa.Integer(), nullable=False), sa.Column("explanation", sa.Text(), nullable=False))
    op.create_table("cost_estimates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("monthly_total", sa.Integer(), nullable=False), sa.Column("annual_total", sa.Integer(), nullable=False), sa.Column("development_total", sa.Integer(), nullable=False), sa.Column("breakdown", sa.JSON(), nullable=False))
    op.create_table("architecture_reports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("pattern", sa.String(120), nullable=False), sa.Column("mermaid", sa.Text(), nullable=False), sa.Column("migration_report", sa.JSON(), nullable=False), sa.Column("html_report", sa.Text(), nullable=False))


def downgrade() -> None:
    for table in ["architecture_reports", "cost_estimates", "recommendation_items", "recommendations", "feature_rules", "compatibility_rules", "recommendation_rules", "technology_knowledge_base", "questionnaire_responses", "projects", "technologies", "technology_categories", "users"]:
        op.drop_table(table)
